In [2]:
import pandas as pd

# Read the Excel file into a pandas DataFrame
df = pd.read_excel('/Users/kexinlin/PycharmProjects/KHGT/NFT.xlsx')
# 将 Date 列转换为 datetime 对象
df['Date'] = pd.to_datetime(df['Date'])

# 将 datetime 转换为 Unix 时间戳（以秒为单位）
df['Date'] = df['Date'].apply(lambda x: int(x.timestamp()))

# 如果你想将 Date 列本身覆盖成时间戳，可以执行下面的语句
# df['Date'] = df['Date'].apply(lambda x: int(x.timestamp()))


In [3]:

df

idCryptoPunk  rarity_rank   tipus           skin  \
0                  0         2023  Female    Mid-skinned   
1                  0         2023  Female    Mid-skinned   
2                  0         2023  Female    Mid-skinned   
3                  0         2023  Female    Mid-skinned   
4                  0         2023  Female    Mid-skinned   
...              ...          ...     ...            ...   
105319          6809         1811    Male  Light-skinned   
105320          6809         1811    Male  Light-skinned   
105321          6809         1811    Male  Light-skinned   
105322          6809         1811    Male  Light-skinned   
105323          6809         1811    Male  Light-skinned   

                                                   traits current_owner  \
0       Blonde Bob, Earring, Green Eye Shadow, Hidden ...      0xE08c32   
1       Blonde Bob, Earring, Green Eye Shadow, Hidden ...      0xE08c32   
2       Blonde Bob, Earring, Green Eye Shadow, Hidden ...      0xE08c32   
3       Blonde Bob, Earring, Green Eye Shadow, Hidden ...      0xE08c32   
4       Blonde Bob, Earring, Green Eye Shadow, Hidden ...      0xE08c32   
...                                                   ...           ...   
105319          Big Beard, Horned Rim Glasses, Peak Spike      0x00668b   
105320          Big Beard, Horned Rim Glasses, Peak Spike      0x00668b   
105321          Big Beard, Horned Rim Glasses, Peak Spike      0x00668b   
105322          Big Beard, Horned Rim Glasses, Peak Spike      0x00668b   
105323          Big Beard, Horned Rim Glasses, Peak Spike      0x00668b   

       idPropietario  TypeTransaction      Owner Reciever  AmountETH  \
0           0xe73a1d    Bid Withdrawn   0xe73a1d        0      321.0   
1           0xe73a1d              Bid   0xe73a1d        0      321.0   
2           0x2e5e22    Bid Withdrawn   0x2e5e22        0      320.0   
3           0x2e5e22              Bid   0x2e5e22        0      320.0   
4           0x2e5e22    Bid Withdrawn   0x2e5e22        0      263.0   
...              ...              ...        ...      ...        ...   
105319             0  Offer Withdrawn          0        0        0.0   
105320             0  Offer Withdrawn          0        0        0.0   
105321             0          Offered          0        0       25.0   
105322        evkort             Sold  TokenAng鈥   evkort        6.5   
105323             0          Offered          0        0        6.5   

        AmountDollar        Date  count  
0          1260000.0  1630713600      3  
1          1140000.0  1630454400      3  
2          1110000.0  1630454400      3  
3          1100000.0  1630454400      3  
4           904481.0  1630454400      3  
...              ...         ...    ...  
105319           0.0  1600214400      3  
105320           0.0  1600214400      3  
105321        9172.0  1600128000      3  
105322        2447.0  1600128000      3  
105323        1366.0  1590624000      3  

[105324 rows x 14 columns]

In [4]:
# Select all rows except the last one
df = df.iloc[:-1]

# df now contains all rows except the last one
df

idCryptoPunk  rarity_rank   tipus           skin  \
0                  0         2023  Female    Mid-skinned   
1                  0         2023  Female    Mid-skinned   
2                  0         2023  Female    Mid-skinned   
3                  0         2023  Female    Mid-skinned   
4                  0         2023  Female    Mid-skinned   
...              ...          ...     ...            ...   
105318          6809         1811    Male  Light-skinned   
105319          6809         1811    Male  Light-skinned   
105320          6809         1811    Male  Light-skinned   
105321          6809         1811    Male  Light-skinned   
105322          6809         1811    Male  Light-skinned   

                                                   traits current_owner  \
0       Blonde Bob, Earring, Green Eye Shadow, Hidden ...      0xE08c32   
1       Blonde Bob, Earring, Green Eye Shadow, Hidden ...      0xE08c32   
2       Blonde Bob, Earring, Green Eye Shadow, Hidden ...      0xE08c32   
3       Blonde Bob, Earring, Green Eye Shadow, Hidden ...      0xE08c32   
4       Blonde Bob, Earring, Green Eye Shadow, Hidden ...      0xE08c32   
...                                                   ...           ...   
105318          Big Beard, Horned Rim Glasses, Peak Spike      0x00668b   
105319          Big Beard, Horned Rim Glasses, Peak Spike      0x00668b   
105320          Big Beard, Horned Rim Glasses, Peak Spike      0x00668b   
105321          Big Beard, Horned Rim Glasses, Peak Spike      0x00668b   
105322          Big Beard, Horned Rim Glasses, Peak Spike      0x00668b   

       idPropietario  TypeTransaction      Owner  Reciever  AmountETH  \
0           0xe73a1d    Bid Withdrawn   0xe73a1d         0      321.0   
1           0xe73a1d              Bid   0xe73a1d         0      321.0   
2           0x2e5e22    Bid Withdrawn   0x2e5e22         0      320.0   
3           0x2e5e22              Bid   0x2e5e22         0      320.0   
4           0x2e5e22    Bid Withdrawn   0x2e5e22         0      263.0   
...              ...              ...        ...       ...        ...   
105318      0x10d6d9         Transfer     evkort  0x10d6d9        0.0   
105319             0  Offer Withdrawn          0         0        0.0   
105320             0  Offer Withdrawn          0         0        0.0   
105321             0          Offered          0         0       25.0   
105322        evkort             Sold  TokenAng鈥    evkort        6.5   

        AmountDollar        Date  count  
0          1260000.0  1630713600      3  
1          1140000.0  1630454400      3  
2          1110000.0  1630454400      3  
3          1100000.0  1630454400      3  
4           904481.0  1630454400      3  
...              ...         ...    ...  
105318           0.0  1600214400      3  
105319           0.0  1600214400      3  
105320           0.0  1600214400      3  
105321        9172.0  1600128000      3  
105322        2447.0  1600128000      3  

[105323 rows x 14 columns]

In [5]:
# Number each unique buyer
df['user_id'] = df['idPropietario'].astype('category').cat.codes + 1

print("Updated DataFrame with new buyer numbers:")
print(df)

Updated DataFrame with new buyer numbers:
        idCryptoPunk  rarity_rank   tipus           skin  \
0                  0         2023  Female    Mid-skinned   
1                  0         2023  Female    Mid-skinned   
2                  0         2023  Female    Mid-skinned   
3                  0         2023  Female    Mid-skinned   
4                  0         2023  Female    Mid-skinned   
...              ...          ...     ...            ...   
105318          6809         1811    Male  Light-skinned   
105319          6809         1811    Male  Light-skinned   
105320          6809         1811    Male  Light-skinned   
105321          6809         1811    Male  Light-skinned   
105322          6809         1811    Male  Light-skinned   

                                                   traits current_owner  \
0       Blonde Bob, Earring, Green Eye Shadow, Hidden ...      0xE08c32   
1       Blonde Bob, Earring, Green Eye Shadow, Hidden ...      0xE08c32   
2       Blon

/Users/kexinlin/anaconda3/envs/py36_env/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [6]:

# Group the dataset by 'buyer' and count the number of transactions for each buyer
buyer_transaction_counts = df.groupby('idPropietario').size().reset_index(name='num_transactions')
# Add a new column 'buyer_id' to number each buyer
buyer_transaction_counts['user_id'] = range(1, len(buyer_transaction_counts) + 1)

# Count the number of unique buyers
num_buyers = buyer_transaction_counts.shape[0]

print("Number of unique buyers:", num_buyers)
print("Buyer-wise transaction counts:")
print(buyer_transaction_counts)


Number of unique buyers: 6416
Buyer-wise transaction counts:
     idPropietario  num_transactions  user_id
0                0             46110        1
1             7478               112        2
2           223332                12        3
3              007                 2        4
4         0d1n.eth                 1        5
...            ...               ...      ...
6411     馃憫馃拵馃檶.e鈥                 7     6412
6412     馃懆馃徎鈥嶐煂.鈥                 4     6413
6413     馃枙馃枙馃枙.e鈥                 9     6414
6414      馃馃懆鈥嶐煔?鈥                10     6415
6415       馃馃馃懇鈥?鈥                 1     6416

[6416 rows x 3 columns]


In [7]:

# Group the dataset by 'TypeTransaction' and count the number of transactions for each type
transaction_type_counts = df.groupby('TypeTransaction').size().reset_index(name='num_transactions')

# Add a new column 'transaction_type_id' to number each type of transaction
transaction_type_counts['transaction_type_id'] = range(1, len(transaction_type_counts) + 1)

# Count the number of unique types of transactions
num_transaction_types = transaction_type_counts.shape[0]

print("Number of unique transaction types:", num_transaction_types)
print("Transaction type-wise transaction counts with transaction type IDs:")
print(transaction_type_counts)


Number of unique transaction types: 9
Transaction type-wise transaction counts with transaction type IDs:
   TypeTransaction  num_transactions  transaction_type_id
0         (Unwrap)              1617                    1
1           (Wrap)              1792                    2
2              Bid             17232                    3
3    Bid Withdrawn             10340                    4
4          Claimed              6809                    5
5  Offer Withdrawn              6298                    6
6          Offered             40286                    7
7             Sold             12126                    8
8         Transfer              8823                    9


## sold

In [8]:

# Filter out transactions of type 'sold'
filtered_df = df[df['TypeTransaction'] != 'Sold']

# Group the filtered dataset by the combination of 'user_id' and 'token_id' and count the number of transactions
transactions_count = filtered_df.groupby(['user_id', 'idCryptoPunk']).size().reset_index(name='num_transactions')

print("Reorganized dataset:")
print(transactions_count)


Reorganized dataset:
       user_id  idCryptoPunk  num_transactions
0            1             0                 3
1            1             1                26
2            1            14                 9
3            1            53                26
4            1            89                31
...        ...           ...               ...
36853     6414          1860                 1
36854     6414          3768                 1
36855     6415          4542                 2
36856     6415          5295                 3
36857     6415          6573                 2

[36858 rows x 3 columns]


In [12]:
from scipy.sparse import csr_matrix
import pickle

# Determine the shape of the sparse matrix
num_users = transactions_count['user_id'].max() + 1
num_tokens = transactions_count['idCryptoPunk'].max() + 1

# Create the sparse matrix
sparse_matrix = csr_matrix((transactions_count['num_transactions'], (transactions_count['user_id'], transactions_count['idCryptoPunk'])), shape=(num_users, num_tokens))

print("Sparse matrix in CSR format:")
print(sparse_matrix)

# Determine the file name
file_name = "sold.pkl"

# Save the CSR matrix as a .pkl file
with open(file_name, 'wb') as f:
    pickle.dump(sparse_matrix, f)

print(f"CSR matrix saved as '{file_name}'")


Sparse matrix in CSR format:
  (1, 0)	3
  (1, 1)	26
  (1, 14)	9
  (1, 53)	26
  (1, 89)	31
  (1, 111)	2
  (1, 116)	13
  (1, 118)	7
  (1, 124)	4
  (1, 138)	16
  (1, 139)	7
  (1, 141)	7
  (1, 143)	4
  (1, 155)	8
  (1, 160)	15
  (1, 161)	27
  (1, 168)	1
  (1, 169)	18
  (1, 172)	2
  (1, 173)	2
  (1, 186)	12
  (1, 195)	1
  (1, 203)	9
  (1, 211)	6
  (1, 226)	2
  :	:
  (6401, 3682)	3
  (6401, 4372)	2
  (6401, 4596)	2
  (6401, 4711)	1
  (6401, 4866)	2
  (6401, 5039)	2
  (6401, 6441)	2
  (6401, 6706)	1
  (6402, 5781)	1
  (6403, 2824)	2
  (6405, 3318)	2
  (6406, 4326)	2
  (6407, 4841)	1
  (6409, 2317)	1
  (6411, 2835)	1
  (6411, 4197)	1
  (6412, 1321)	1
  (6412, 3569)	2
  (6414, 72)	2
  (6414, 290)	2
  (6414, 1860)	1
  (6414, 3768)	1
  (6415, 4542)	2
  (6415, 5295)	3
  (6415, 6573)	2
CSR matrix saved as 'sold.pkl'


In [23]:
from scipy.sparse import csr_matrix
import numpy as np
import pickle

# Define the transaction types to iterate over
transaction_types = ['Sold', 'Bid', 'Offer Withdrawn', 'Offered', 'Bid Withdrawn']

# Number of users is exactly 6416, as user_id ranges from 1 to 6416
num_users = 6416

# Determine the number of unique tokens
num_tokens = df['idCryptoPunk'].max() + 1  # Assuming token IDs are zero-indexed

# Iterate over each transaction type
for transaction_type in transaction_types:
    # Filter the DataFrame for the current transaction type
    filtered_df = df[df['TypeTransaction'] == transaction_type]

    # Group the filtered dataset by 'user_id' and 'idCryptoPunk' and get the last timestamp
    last_interactions = filtered_df.groupby(['user_id', 'idCryptoPunk'])['Date'].max().reset_index()

    # Initialize lists to store data for creating the sparse matrix
    row_indices = []
    col_indices = []
    data = []

    # Fill the lists with the last interaction timestamps
    for _, row in last_interactions.iterrows():
        user_id = row['user_id'] - 1  # Adjusting for zero-based indexing
        token_id = row['idCryptoPunk']
        timestamp = row['Date']
        
        row_indices.append(user_id)
        col_indices.append(token_id)
        data.append(timestamp)

    # Create the sparse matrix
    sparse_matrix = csr_matrix((data, (row_indices, col_indices)), shape=(num_users, num_tokens))

    # Replace all NaN (missing) values with 0 in the sparse matrix
    sparse_matrix.data = np.nan_to_num(sparse_matrix.data, nan=0.0)

    # Print the shape of the sparse matrix
    print(f"Sparse matrix for '{transaction_type}' - shape: {sparse_matrix.shape}")

    # Determine the file name
    file_name = f"{transaction_type.lower()}_item_interactions.pkl"

    # Save the CSR matrix as a .pkl file
    with open(file_name, 'wb') as f:
        pickle.dump(sparse_matrix, f)

    print(f"CSR matrix for '{transaction_type}' saved as '{file_name}'")


Sparse matrix for 'Sold' - shape: (6416, 6810)
CSR matrix for 'Sold' saved as 'sold_item_interactions.pkl'
Sparse matrix for 'Bid' - shape: (6416, 6810)
CSR matrix for 'Bid' saved as 'bid_item_interactions.pkl'
Sparse matrix for 'Offer Withdrawn' - shape: (6416, 6810)
CSR matrix for 'Offer Withdrawn' saved as 'offer withdrawn_item_interactions.pkl'
Sparse matrix for 'Offered' - shape: (6416, 6810)
CSR matrix for 'Offered' saved as 'offered_item_interactions.pkl'
Sparse matrix for 'Bid Withdrawn' - shape: (6416, 6810)
CSR matrix for 'Bid Withdrawn' saved as 'bid withdrawn_item_interactions.pkl'


In [24]:
from scipy.sparse import csr_matrix
import numpy as np
import pickle

# Define the transaction types to iterate over
transaction_types = ['Sold', 'Bid', 'Offer Withdrawn', 'Offered', 'Bid Withdrawn']

# Number of users is exactly 6416, as user_id ranges from 1 to 6416
num_users = 6416

# Determine the number of unique tokens
num_tokens = df['idCryptoPunk'].max() + 1  # Assuming token IDs are zero-indexed

# Iterate over each transaction type
for transaction_type in transaction_types:
    # Filter the DataFrame for the current transaction type
    filtered_df = df[df['TypeTransaction'] == transaction_type]

    # Group the filtered dataset by 'user_id' and 'idCryptoPunk' and get the last timestamp
    last_interactions = filtered_df.groupby(['user_id', 'idCryptoPunk'])['Date'].max().reset_index()

    # Initialize lists to store data for creating the sparse matrix
    row_indices = []
    col_indices = []
    data = []

    # Fill the lists with the last interaction timestamps
    for _, row in last_interactions.iterrows():
        user_id = row['user_id'] - 1  # Adjusting for zero-based indexing
        token_id = row['idCryptoPunk']
        timestamp = row['Date']
        
        row_indices.append(user_id)
        col_indices.append(token_id)
        data.append(timestamp)

    # Create the sparse matrix
    sparse_matrix = csr_matrix((data, (row_indices, col_indices)), shape=(num_users, num_tokens))

    # Replace all NaN (missing) values with 0 in the sparse matrix
    sparse_matrix.data = np.nan_to_num(sparse_matrix.data, nan=0.0)

    # Print the sparse matrix
    print(f"Sparse matrix for '{transaction_type}':")
    print(sparse_matrix)

    # Convert sparse matrix to a dense matrix and print it
    dense_matrix = sparse_matrix.toarray()
    print(f"Converted dense matrix for '{transaction_type}':")
    print(dense_matrix)

    # Print the shape of the sparse matrix
    print(f"Sparse matrix shape for '{transaction_type}': {sparse_matrix.shape}")

  

Sparse matrix for 'Sold':
  (1, 1071)	1564272000
  (1, 1215)	1547942400
  (1, 1244)	1581033600
  (1, 1650)	1579564800
  (1, 2043)	1581206400
  (1, 2154)	1594252800
  (1, 2374)	1580601600
  (1, 3268)	1581033600
  (1, 3471)	1582588800
  (1, 4660)	1564531200
  (1, 4811)	1569628800
  (1, 5179)	1576540800
  (1, 5285)	1600560000
  (1, 5544)	1576886400
  (1, 5760)	1589846400
  (1, 5920)	1548201600
  (1, 6143)	1572048000
  (1, 6749)	1572825600
  (2, 1071)	1627776000
  (2, 1812)	1596153600
  (2, 2511)	1627171200
  (2, 3420)	1627776000
  (2, 3862)	1626393600
  (2, 4216)	1602460800
  (2, 6710)	1600905600
  :	:
  (6405, 6248)	1611446400
  (6406, 4841)	1613865600
  (6407, 1857)	1527724800
  (6409, 1585)	1614988800
  (6409, 2317)	1624579200
  (6409, 4079)	1613174400
  (6409, 4399)	1626480000
  (6409, 6648)	1627689600
  (6410, 4197)	1617494400
  (6410, 5077)	1617926400
  (6411, 1321)	1617753600
  (6411, 2632)	1617062400
  (6411, 3569)	1617926400
  (6411, 6312)	1617235200
  (6412, 1966)	1613260800
  (

In [29]:
import pandas as pd
from scipy.sparse import csr_matrix
import pickle

def determine_max_shape(df):
    max_user_id = df['user_id'].max()
    max_token_id = df['idCryptoPunk'].max()
    return max_user_id, max_token_id + 1  # 只对 max_token_id + 1

def process_and_save(df, transaction_type, max_shape):
    # 过滤出给定类型的交易
    filtered_df = df[df['TypeTransaction'] == transaction_type]

    # 对每个 (user_id, idCryptoPunk) 组合，保留最新的时间戳
    latest_transactions = filtered_df.sort_values(by='user_id').groupby(['user_id', 'idCryptoPunk']).tail(1)
    max_user_id = max_shape[0] - 1
    latest_transactions = latest_transactions[latest_transactions['user_id'] <= max_user_id]

    print(f"Reorganized dataset for '{transaction_type}' (latest timestamps):")
    print(latest_transactions[['user_id', 'idCryptoPunk', 'Date']])

    # 使用预定的最大形状创建稀疏矩阵
    sparse_matrix = csr_matrix((latest_transactions['Date'], 
                                (latest_transactions['user_id'], latest_transactions['idCryptoPunk'])), 
                                shape=max_shape)

    # 打印稀疏矩阵的形状
    matrix_shape = sparse_matrix.shape
    print(f"Sparse matrix in CSR format for '{transaction_type}' has shape: {matrix_shape}")
    print(f"Portion of the dense matrix for '{transaction_type}':\n", sparse_matrix.toarray()[:6416, :10])

    # 确定文件名
    file_name = f"{transaction_type.lower()}"

    # 将 CSR 矩阵保存为 .pkl 文件
    with open(file_name, 'wb') as f:
        pickle.dump(sparse_matrix, f)

    print(f"CSR matrix saved as '{file_name}'")
    return matrix_shape

# 确定所有交易类型的最大形状
max_shape = determine_max_shape(df)

# 字典来存储每个交易类型的形状
shapes_dict = {}

# 使用确定的最大形状对每种交易类型应用操作
for transaction_type in ['Sold', 'Bid', 'Offer Withdrawn', 'Offered', 'Bid Withdrawn']:
    shape = process_and_save(df, transaction_type, max_shape)
    shapes_dict[transaction_type] = shape

# 打印所有保存的 CSR 矩阵的形状
print("Shapes of saved CSR matrices:")
for transaction_type, shape in shapes_dict.items():
    print(f"{transaction_type}: {shape}")


Reorganized dataset for 'Sold' (latest timestamps):
       user_id  idCryptoPunk        Date
78837        2          5285  1600560000
92766        2          6143  1572048000
26055        2          2154  1594252800
49171        2          3471  1582588800
70928        2          4811  1569628800
...        ...           ...         ...
26098     6414          2158  1608595200
54728     6414          3768  1610582400
46529     6415          3334  1620604800
79044     6415          5295  1623888000
67142     6415          4542  1619740800

[12019 rows x 3 columns]
Sparse matrix in CSR format for 'Sold' has shape: (6416, 6810)
Portion of the dense matrix for 'Sold':
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
CSR matrix saved as 'sold'
Reorganized dataset for 'Bid' (latest timestamps):
        user_id  idCryptoPunk        Date
14739         2          1386  1610841600
45299         2          3268  1580947200
77

In [1]:
import pickle
import numpy as np
def load_and_inspect(file_name):
    with open(file_name, 'rb') as f:
        sparse_matrix = pickle.load(f)

    # Convert sparse matrix to dense format
    dense_matrix = sparse_matrix.toarray()

    print(f"Contents of the matrix from '{file_name}':")
    
    # Display basic summary
    print(f"Shape: {dense_matrix.shape}")
    print(f"Data type: {dense_matrix.dtype}")
    print(f"Non-zero entries: {np.count_nonzero(dense_matrix)}")

    # Display a portion of the matrix
    print(f"Top-left corner of the matrix:\n{dense_matrix[:5, :5]}")
    print("...")
    print(f"Bottom-right corner of the matrix:\n{dense_matrix[-5:, -5:]}")

# List of file names
# file_names = ['sold', 'bid', 'offer withdrawn', 'offered', 'bid withdrawn']
file_names = [ 'trn_neg', 'trn_neutral', 'trn_pos', 'trn_tip','tst_int']

# Inspect each matrix
for file_name in file_names:
    load_and_inspect("Datasets/Yelp/"+file_name)


Contents of the matrix from 'Datasets/Yelp/trn_neg':
Shape: (19800, 22734)
Data type: float64
Non-zero entries: 198106
Top-left corner of the matrix:
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  1.41887985e+09]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]]
...
Bottom-right corner of the matrix:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Contents of the matrix from 'Datasets/Yelp/trn_neutral':
Shape: (19800, 22734)
Data type: float64
Non-zero entries: 238880
Top-left corner of the matrix:
[[0.00000000e+00 0.00000000e+00 1.51225197e+09 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.0

AttributeError: 'list' object has no attribute 'toarray'

In [14]:
import pandas as pd
from scipy.sparse import csr_matrix
from scipy.sparse import save_npz

# Assume 'df' is your DataFrame containing all transactions

# Transaction types
transaction_types = ['Sold', 'Bid', 'Offer Withdrawn', 'Offered', 'Bid Withdrawn']

for transaction_type in transaction_types:
    # Filter transactions by type
    filtered_transactions = df[df['TypeTransaction'] == transaction_type]

    # Group the filtered dataset by the combination of 'user_id' and 'idCryptoPunk' and count the number of transactions
    transactions_count = filtered_transactions.groupby(['user_id', 'idCryptoPunk']).size().reset_index(name='num_transactions')

    print(f"Reorganized dataset for '{transaction_type}':")
    print(transactions_count)

    # Determine the shape of the sparse matrix
    num_users = transactions_count['user_id'].max() + 1
    num_tokens = transactions_count['idCryptoPunk'].max() + 1

    # Create the sparse matrix for the current transaction type
    sparse_matrix = csr_matrix((transactions_count['num_transactions'], (transactions_count['user_id'], transactions_count['idCryptoPunk'])), shape=(num_users, num_tokens))

    print(f"Sparse matrix in CSR format for {transaction_type}:")
    print(sparse_matrix)

    # Determine the file name based on transaction type
    file_name = f"{transaction_type.lower().replace(' ', '_')}.npz"

    # Save the CSR matrix
    save_npz(file_name, sparse_matrix)

    print(f"CSR matrix for {transaction_type} saved as '{file_name}'")


Reorganized dataset for 'Sold':
       user_id  idCryptoPunk  num_transactions
0            2          1071                 1
1            2          1215                 1
2            2          1244                 1
3            2          1650                 1
4            2          2043                 1
...        ...           ...               ...
12015     6414          3768                 1
12016     6415          3334                 1
12017     6415          4542                 1
12018     6415          5295                 1
12019     6416          3520                 1

[12020 rows x 3 columns]
Sparse matrix in CSR format for Sold:
  (2, 1071)	1
  (2, 1215)	1
  (2, 1244)	1
  (2, 1650)	1
  (2, 2043)	1
  (2, 2154)	1
  (2, 2374)	1
  (2, 3268)	1
  (2, 3471)	1
  (2, 4660)	1
  (2, 4811)	1
  (2, 5179)	1
  (2, 5285)	1
  (2, 5544)	1
  (2, 5760)	1
  (2, 5920)	1
  (2, 6143)	1
  (2, 6749)	1
  (3, 1071)	1
  (3, 1812)	1
  (3, 2511)	1
  (3, 3420)	1
  (3, 3862)	1
  (3, 4216)	1
  (3

In [13]:
import pandas as pd
from scipy.sparse import csr_matrix
from scipy.sparse import save_npz

# Assume 'df' is your DataFrame containing all transactions

# Transaction types
transaction_types = ['Sold', 'Bid', 'Offer Withdrawn', 'Offered', 'Bid Withdrawn']

for transaction_type in transaction_types:
    # Filter transactions by type
    filtered_transactions = df[df['TypeTransaction'] == transaction_type]

    # Group the filtered dataset by the combination of 'user_id' and 'idCryptoPunk' and count the number of transactions
    transactions_count = filtered_transactions.groupby(['user_id', 'idCryptoPunk']).size().reset_index(name='num_transactions')

    print(f"Reorganized dataset for '{transaction_type}':")
    print(transactions_count)

    # Determine the shape of the sparse matrix
    num_users = transactions_count['user_id'].max() + 1
    num_tokens = transactions_count['idCryptoPunk'].max() + 1

    # Output the maximum user ID and ID cryptopunk
    print(f"Maximum user ID for {transaction_type}: {num_users - 1}")
    print(f"Maximum ID CryptoPunk for {transaction_type}: {num_tokens - 1}")

    # Create the sparse matrix for the current transaction type
    sparse_matrix = csr_matrix((transactions_count['num_transactions'], (transactions_count['user_id'], transactions_count['idCryptoPunk'])), shape=(num_users, num_tokens))

    print(f"Sparse matrix in CSR format for {transaction_type}:")
    print(sparse_matrix)

    # Determine the file name based on transaction type
    file_name = f"{transaction_type.lower().replace(' ', '_')}.npz"

    # Save the CSR matrix
    save_npz(file_name, sparse_matrix)

    print(f"CSR matrix for {transaction_type} saved as '{file_name}'")


Reorganized dataset for 'Sold':
       user_id  idCryptoPunk  num_transactions
0            2          1071                 1
1            2          1215                 1
2            2          1244                 1
3            2          1650                 1
4            2          2043                 1
...        ...           ...               ...
12015     6414          3768                 1
12016     6415          3334                 1
12017     6415          4542                 1
12018     6415          5295                 1
12019     6416          3520                 1

[12020 rows x 3 columns]
Maximum user ID for Sold: 6416
Maximum ID CryptoPunk for Sold: 6809
Sparse matrix in CSR format for Sold:
  (2, 1071)	1
  (2, 1215)	1
  (2, 1244)	1
  (2, 1650)	1
  (2, 2043)	1
  (2, 2154)	1
  (2, 2374)	1
  (2, 3268)	1
  (2, 3471)	1
  (2, 4660)	1
  (2, 4811)	1
  (2, 5179)	1
  (2, 5285)	1
  (2, 5544)	1
  (2, 5760)	1
  (2, 5920)	1
  (2, 6143)	1
  (2, 6749)	1
  (3, 1071)	1
  (3, 

In [12]:
import pandas as pd
from scipy.sparse import csr_matrix
import pickle

def process_and_save(df, transaction_type):
    # Filter out transactions of the given type
    filtered_df = df[df['TypeTransaction'] == transaction_type]

    # Convert 'Date' from datetime to a numerical timestamp (e.g., days since the start of the dataset)
    filtered_df['Date'] = pd.to_datetime(filtered_df['Date'])
    # Assuming you want to use days as your unit, you can subtract the minimum date and convert to days
    min_date = filtered_df['Date'].min()
    filtered_df['transactionTime'] = (filtered_df['Date'] - min_date).dt.days

    # Group the filtered dataset by 'user_id' and 'idCryptoPunk', selecting the last transaction time
    last_transactions = filtered_df.groupby(['user_id', 'idCryptoPunk'])['transactionTime'].max().reset_index()

    # Ensure user_id and idCryptoPunk are treated as categorical for proper indexing
    last_transactions['user_id'] = pd.Categorical(last_transactions['user_id'])
    last_transactions['idCryptoPunk'] = pd.Categorical(last_transactions['idCryptoPunk'])

    # Determine the shape of the sparse matrix
    num_users = last_transactions['user_id'].cat.codes.max() + 1
    num_tokens = last_transactions['idCryptoPunk'].cat.codes.max() + 1

    # Create the sparse matrix, using transaction times as values
    sparse_matrix = csr_matrix((last_transactions['transactionTime'],
                                (last_transactions['user_id'].cat.codes, last_transactions['idCryptoPunk'].cat.codes)),
                               shape=(num_users, num_tokens))

    # Save the CSR matrix as a .pkl file
    file_name = f"{transaction_type.lower()}.pkl"
    with open(file_name, 'wb') as f:
        pickle.dump(sparse_matrix, f)

    print(f"CSR matrix saved as '{file_name}'")

# Apply the operation for each transaction type
transaction_types = ['Sold', 'Bid', 'Offer Withdrawn', 'Offered', 'Bid Withdrawn']
for transaction_type in transaction_types:
    process_and_save(df, transaction_type)


CSR matrix saved as 'sold.pkl'
CSR matrix saved as 'bid.pkl'
CSR matrix saved as 'offer withdrawn.pkl'
CSR matrix saved as 'offered.pkl'
CSR matrix saved as 'bid withdrawn.pkl'


C:\Users\DT\PycharmProjects\cs61b\.venv\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\DT\PycharmProjects\cs61b\.venv\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]


In [215]:
import pickle
from scipy.sparse import csr_matrix
# Load the CSR matrix from the .pkl file
file_name = "sold.pkl"  # Replace with the correct file name as needed
with open(file_name, 'rb') as f:
    sparse_matrix = pickle.load(f)

# Print the data type
print(f"Loaded data type: {type(sparse_matrix)}")

# Print the content in the desired format
print("Data content:")
print(sparse_matrix)


FileNotFoundError: [Errno 2] No such file or directory: 'sold.pkl'

In [216]:
import pandas as pd
from scipy.sparse import csr_matrix, save_npz

def convert_to_epoch(time_series):
    """Converts a pandas Series of datetime objects to epoch time."""
    return time_series.astype('int64') // 10**9

def process_and_save(df, transaction_type, test_users_last_sold):
    # Filter out transactions of the given type
    filtered_df = df[df['TypeTransaction'] == transaction_type]

    # Exclude last 'sold' transactions from the training set
    if transaction_type != 'Sold':
        filtered_df = filtered_df[~filtered_df.index.isin(test_users_last_sold.index)]

    # Convert 'Date' to epoch time
    filtered_df['EpochTime'] = convert_to_epoch(filtered_df['Date'])

    # Group by 'user_id' and 'idCryptoPunk', selecting the last transaction time
    last_transactions = filtered_df.groupby(['user_id', 'idCryptoPunk'])['EpochTime'].max().reset_index()

    # Ensure user_id and idCryptoPunk are treated as categorical for proper indexing
    last_transactions['user_id'] = pd.Categorical(last_transactions['user_id'])
    last_transactions['idCryptoPunk'] = pd.Categorical(last_transactions['idCryptoPunk'])

    # Create the sparse matrix
    num_users = df['user_id'].nunique()
    num_tokens = df['idCryptoPunk'].nunique()
    sparse_matrix = csr_matrix((last_transactions['EpochTime'],
                                (last_transactions['user_id'].cat.codes, last_transactions['idCryptoPunk'].cat.codes)),
                               shape=(num_users, num_tokens))

    # Save the CSR matrix
    file_name = f"{transaction_type.lower()}.npz"
    save_npz(file_name, sparse_matrix)
    print(f"CSR matrix saved as '{file_name}'")



# Convert 'Date' column to datetime
df['Date'] = pd.to_datetime(df['Date'])
df['user_id'] = df['idPropietario'].astype('category').cat.codes + 1

# Identify the last 'sold' transaction for each user
last_sold_transactions = df[df['TypeTransaction'] == 'Sold'].groupby('user_id').apply(lambda x: x.nlargest(1, 'Date'))
test_users_last_sold = last_sold_transactions.set_index('user_id')

# Apply the operation for each transaction type
transaction_types = ['Sold', 'Bid', 'Offer Withdrawn', 'Offered', 'Bid Withdrawn']
for transaction_type in transaction_types:
    process_and_save(df, transaction_type, test_users_last_sold)


NameError: name 'df' is not defined

In [217]:
df1=df

NameError: name 'df' is not defined

In [218]:
df1['Date'] = df1['Date'].str.split(' ').str[0]


NameError: name 'df1' is not defined

In [219]:
df1

NameError: name 'df1' is not defined

In [220]:
df.Date

NameError: name 'df' is not defined

In [221]:


# Now, convert the 'Date' column to datetime
df['Date'] = pd.to_datetime(df['Date'])

NameError: name 'df' is not defined

In [222]:
import pandas as pd
from scipy.sparse import csr_matrix
from scipy.sparse import save_npz

# Assume 'df' is your DataFrame containing all transactions

# Ensure the 'Date' column is in datetime format
df['Date'] = pd.to_datetime(df['Date'])

# Transaction types
transaction_types = ['Sold', 'Bid', 'Offer Withdrawn', 'Offered', 'Bid Withdrawn']

# Initialize a list to store test data for 'Sold' transactions
test_data_sold = []

for transaction_type in transaction_types:
    # Filter transactions by type
    filtered_transactions = df[df['TypeTransaction'] == transaction_type]

    if transaction_type == 'Sold':
        # Sort transactions to ensure the last transaction per user is identified correctly
        sorted_transactions = filtered_transactions.sort_values(by=['user_id', 'Date'])

        # Identify the last transaction for each user
        last_transaction_per_user = sorted_transactions.drop_duplicates('user_id', keep='last')

        # Add last transactions to the test dataset
        test_data_sold.extend(last_transaction_per_user[['user_id', 'idCryptoPunk']].values.tolist())

        # Remove the last transactions from the dataset to create the training set
        filtered_transactions = sorted_transactions.drop(last_transaction_per_user.index)

    # Group the filtered dataset by 'user_id' and 'idCryptoPunk' and take the maximum 'Date' of transactions
    transactions_date = filtered_transactions.groupby(['user_id', 'idCryptoPunk'])['Date'].max().reset_index()

    # Convert dates to a numerical format (e.g., ordinal date) for use in the sparse matrix
    transactions_date['Date'] = transactions_date['Date'].apply(lambda x: x.toordinal())

    # Determine the shape of the sparse matrix
    num_users = transactions_date['user_id'].max() + 1
    num_tokens = transactions_date['idCryptoPunk'].max() + 1

    # Create the sparse matrix for the current transaction type, using the latest transaction date
    sparse_matrix = csr_matrix((transactions_date['Date'], (transactions_date['user_id'], transactions_date['idCryptoPunk'])), shape=(num_users, num_tokens))

    # Determine the file name based on transaction type
    file_name = f"{transaction_type.lower().replace(' ', '_')}.npz"

    # Save the CSR matrix
    save_npz(file_name, sparse_matrix)

    print(f"CSR matrix for {transaction_type} saved as '{file_name}'")

# Handle the case where some users did not sell anything
users_with_sold_transactions = set([x[0] for x in test_data_sold])
all_users = set(df['user_id'].unique())
users_without_sold = all_users - users_with_sold_transactions
test_data_sold.extend([(user, None) for user in users_without_sold])

print("Test dataset for 'Sold' transactions (user_id, idCryptoPunk):")
print(test_data_sold)


NameError: name 'df' is not defined

In [223]:
import pandas as pd
from scipy.sparse import csr_matrix
from scipy.sparse import save_npz
import pandas as pd
from scipy.sparse import csr_matrix
from scipy.sparse import save_npz
import pickle

# Ensure the 'Date' column is in datetime format
df['Date'] = pd.to_datetime(df['Date'])

# Transaction types
transaction_types = ['Sold', 'Bid', 'Offer Withdrawn', 'Offered', 'Bid Withdrawn']

# Initialize a list to store test data for 'Sold' transactions
test_data_sold = []

for transaction_type in transaction_types:
    # Filter transactions by type
    filtered_transactions = df[df['TypeTransaction'] == transaction_type]

    if (transaction_type == 'Sold') and not filtered_transactions.empty:
        # Sort transactions to ensure the last transaction per user is identified correctly
        sorted_transactions = filtered_transactions.sort_values(by=['user_id', 'Date'])

        # Identify the last transaction for each user
        last_transaction_per_user = sorted_transactions.drop_duplicates('user_id', keep='last')

        # Add last transactions to the test dataset
        test_data_sold.extend(last_transaction_per_user[['user_id', 'idCryptoPunk']].values.tolist())

        # Remove the last transactions from the dataset to create the training set
        filtered_transactions = sorted_transactions.drop(last_transaction_per_user.index)

    # Group the filtered dataset by 'user_id' and 'idCryptoPunk' and take the maximum 'Date' of transactions
    transactions_date = filtered_transactions.groupby(['user_id', 'idCryptoPunk'])['Date'].max().reset_index()

    # Convert dates to a numerical format (e.g., ordinal date) for use in the sparse matrix
    transactions_date['Date'] = transactions_date['Date'].apply(lambda x: x.toordinal())

    # Determine the shape of the sparse matrix
    num_users = transactions_date['user_id'].max() + 1
    num_tokens = transactions_date['idCryptoPunk'].max() + 1

    # Create the sparse matrix for the current transaction type, using the latest transaction date
    sparse_matrix = csr_matrix((transactions_date['Date'], (transactions_date['user_id'], transactions_date['idCryptoPunk'])), shape=(num_users, num_tokens))

    # Determine the file name based on transaction type
    file_name = f"{transaction_type.lower().replace(' ', '_')}.npz"

    # Save the CSR matrix
    save_npz(file_name, sparse_matrix)

    print(f"CSR matrix for {transaction_type} saved as '{file_name}'")

# Handle the case where some users did not sell anything
users_with_sold_transactions = set([x[0] for x in test_data_sold])
all_users = set(df['user_id'].unique())
users_without_sold = all_users - users_with_sold_transactions
test_data_sold.extend([(user, None) for user in users_without_sold])

# Ensure all pairs are consistent by converting any lists in the test_data_sold to tuples
test_data_sold = [tuple(pair) for pair in test_data_sold]

# Extract the sequence of items (idCryptoPunk) for each user
item_sequence = [item if item is not None else None for _, item in sorted(test_data_sold)]

print("Sequence of items corresponding to each user (without user IDs):")
print(item_sequence)

# Export the item_sequence to a .pkl file
with open("item_sequence.pkl", "wb") as f:
    pickle.dump(item_sequence, f)

print("item_sequence has been exported to 'item_sequence.pkl'")

NameError: name 'df' is not defined

In [224]:
import numpy as np

# Convert test_data_sold to a NumPy array
# Assuming all user IDs are integers, and None is replaced with a specific integer, e.g., -1
test_data_array = np.array([(user, -1 if punk is None else punk) for user, punk in test_data_sold], dtype=np.int64)

# Save the NumPy array as an .npz file
np.savez('test_data_sold.npz', test_data=item_sequence)


NameError: name 'test_data_sold' is not defined

In [225]:
import numpy as np

# Convert test_data_sold to a NumPy array
# Assuming all user IDs are integers, and None is replaced with a specific integer, e.g., -1
test_data_array = np.array([(user, -1 if punk is None else punk) for user, punk in test_data_sold], dtype=np.int64)

# Save the NumPy array as an .npz file
np.savez('test_data_sold.npz', test_data=test_data_array)


NameError: name 'test_data_sold' is not defined

In [226]:
import pandas as pd
from scipy.sparse import csr_matrix, save_npz

def convert_to_epoch(time_series):
    """Converts a pandas Series of datetime objects to epoch time."""
    return time_series.astype('int64') // 10**9

def process_and_save(df, transaction_type, test_users_last_sold):
    # Filter out transactions of the given type
    filtered_df = df[df['TypeTransaction'] == transaction_type]

    # Exclude last 'sold' transactions from the training set
    if transaction_type != 'Sold':
        filtered_df = filtered_df[~filtered_df.index.isin(test_users_last_sold)]

    # Convert 'Date' to epoch time
    filtered_df['EpochTime'] = convert_to_epoch(filtered_df['Date'])

    # Group by 'user_id' and 'idCryptoPunk', selecting the last transaction time
    last_transactions = filtered_df.groupby(['user_id', 'idCryptoPunk'])['EpochTime'].max().reset_index()

    # Ensure user_id and idCryptoPunk are treated as categorical for proper indexing
    last_transactions['user_id'] = pd.Categorical(last_transactions['user_id'])
    last_transactions['idCryptoPunk'] = pd.Categorical(last_transactions['idCryptoPunk'])

    # Create the sparse matrix
    num_users = df['user_id'].nunique()
    num_tokens = df['idCryptoPunk'].nunique()
    sparse_matrix = csr_matrix((last_transactions['EpochTime'],
                                (last_transactions['user_id'].cat.codes, last_transactions['idCryptoPunk'].cat.codes)),
                               shape=(num_users, num_tokens))

    # Save the CSR matrix
    file_name = f"{transaction_type.lower()}.npz"
    save_npz(file_name, sparse_matrix)
    print(f"CSR matrix saved as '{file_name}'")

# Load your DataFrame 'df' here
# df = pd.read_csv("your_data.csv")

# Convert 'Date' column to datetime
df['Date'] = pd.to_datetime(df['Date'])
df['user_id'] = df['idPropietario'].astype('category').cat.codes + 1

# Identify the last 'sold' transaction for each user
last_sold_transactions = df[df['TypeTransaction'] == 'Sold'].groupby('user_id').apply(lambda x: x.nlargest(1, 'Date'))
test_users_last_sold = last_sold_transactions.index.values

# Apply the operation for each transaction type
transaction_types = ['Sold', 'Bid', 'Offer Withdrawn', 'Offered', 'Bid Withdrawn']
for transaction_type in transaction_types:
    process_and_save(df, transaction_type, test_users_last_sold)


NameError: name 'df' is not defined

In [227]:
import numpy as np

# Save the array as npz
np.savez("test_users_last_sold.npz", test_users_last_sold=test_users_last_sold)


NameError: name 'test_users_last_sold' is not defined

In [228]:
predir = '/content/'
behs = ['bid withdrawn.npz', 'offered.npz', 'offer withdrawn.npz', 'bid.npz', 'sold.npz']

trnfile = predir
tstfile = predir + 'test_users_last_sold.npz'


In [229]:
import scipy.sparse as sp
import numpy as np

In [230]:
def timeProcess(trnMats):
	mi = 1e15
	ma = 0
	for i in range(len(trnMats)):
		minn = np.min(trnMats[i].data)
		maxx = np.max(trnMats[i].data)
		mi = min(mi, minn)
		ma = max(ma, maxx)
	maxTime = 0
	for i in range(len(trnMats)):
		newData = ((trnMats[i].data - mi) / (3600*24*1)).astype(np.int32)
		maxTime = max(np.max(newData), maxTime)
		trnMats[i] = csr_matrix((newData, trnMats[i].indices, trnMats[i].indptr), shape=trnMats[i].shape)
	print('MAX TIME', maxTime)
	return trnMats, maxTime + 1

In [231]:
def LoadData():
    trnMats = []
    for i in range(len(behs)):
        beh = behs[i]
        path = trnfile + beh
        with open(path, 'rb') as fs:
            mat = sp.load_npz(fs)
        trnMats.append(mat)

    # Process labels for the 'buy' scenario, assuming it corresponds to the last behavior
    trnLabel = 1 * (trnMats[-1] != 0) if trnMats else None

    # Placeholder for your actual time processing function
    trnMats, maxTime = timeProcess(trnMats)

    # Test set
    with np.load(tstfile, allow_pickle=True) as data:
        tstInt1 = data['test_users_last_sold']


    # Determine the unique user IDs
    user_ids = set(pair[0] for pair in tstInt1)

    # Create a list with user purchase status
    max_user_id = max(user_ids)
    user_purchases = [None] * (max_user_id + 1)

    for user_id in user_ids:
        user_purchases[user_id] = user_id

    tstInt = user_purchases
    tstStat = (tstInt!=None)
    tstUsrs = np.reshape(np.argwhere(tstStat), [-1])



    return trnMats, tstInt, trnLabel, tstUsrs, len(behs), maxTime

In [232]:
trnMats = []
for i in range(len(behs)):
    beh = behs[i]
    path = trnfile + beh
    with open(path, 'rb') as fs:
        mat = sp.load_npz(fs)
    trnMats.append(mat)

FileNotFoundError: [Errno 2] No such file or directory: '/content/bid withdrawn.npz'

In [ ]:
LoadData()

In [233]:
uids = trnMats[:, 0]  # User IDs
iids = trnMats[:, 1]  # Item IDs

TypeError: list indices must be integers or slices, not tuple

In [234]:
import scipy.sparse as sp

def extract_user_item_pairs(trnMats):
    user_item_pairs = []
    for mat in trnMats:
        # Find the indices of non-zero entries in the sparse matrix.
        user_indices, item_indices = mat.nonzero()

        # Pair each user index with its corresponding item index.
        pairs = list(zip(user_indices, item_indices))
        user_item_pairs.extend(pairs)

    return user_item_pairs

# Assuming trnMats is populated as shown previously
user_item_pairs = extract_user_item_pairs(trnMats)

# If you need to transform these pairs into tensors for PyTorch
import torch
user_ids, item_ids = zip(*user_item_pairs)  # Unzip the pairs
user_ids_tensor = torch.tensor(user_ids, dtype=torch.long)  # Convert to tensor
item_ids_tensor = torch.tensor(item_ids, dtype=torch.long)  # Convert to tensor


ModuleNotFoundError: No module named 'torch'

In [235]:
item_ids_tensor

NameError: name 'item_ids_tensor' is not defined

In [236]:
LoadData()[1]

FileNotFoundError: [Errno 2] No such file or directory: '/content/bid withdrawn.npz'

In [237]:
with np.load(tstfile, allow_pickle=True) as data:
    tstInt = data['test_users_last_sold']

FileNotFoundError: [Errno 2] No such file or directory: '/content/test_users_last_sold.npz'

In [238]:
len(tstInt)

NameError: name 'tstInt' is not defined

In [239]:
tstStat = (tstInt!=None)
tstStat

NameError: name 'tstInt' is not defined

In [240]:
# Test set
with np.load(tstfile, allow_pickle=True) as data:
    tstInt1 = data['test_users_last_sold']


# Determine the unique user IDs
user_ids = set(pair[0] for pair in tstInt1)

# Create a list with user purchase status
max_user_id = max(user_ids)
user_purchases = [None] * (max_user_id + 1)

for user_id in user_ids:
    user_purchases[user_id] = user_id

tstInt = user_purchases
tstStat = [user_id for user_id in user_purchases if user_id is not None]

FileNotFoundError: [Errno 2] No such file or directory: '/content/test_users_last_sold.npz'

In [241]:
tstStat

NameError: name 'tstStat' is not defined

In [242]:
tstInt[-5:]

NameError: name 'tstInt' is not defined

In [243]:
len(tstInt)

NameError: name 'tstInt' is not defined

In [244]:
import pickle
# Test set
with np.load('/content/test_users_last_sold.npz', allow_pickle=True) as data:
    tstInt1 = data['test_users_last_sold']


# Determine the unique user IDs
user_ids = set(pair[0] for pair in tstInt1)

FileNotFoundError: [Errno 2] No such file or directory: '/content/test_users_last_sold.npz'

In [245]:
len(user_ids)

NameError: name 'user_ids' is not defined

In [246]:
import pickle
path =  '/content/tst_int'
with open(path, 'rb') as fs:
  tstInt = np.array(pickle.load(fs))


FileNotFoundError: [Errno 2] No such file or directory: '/content/tst_int'

In [247]:
len(tstInt)

NameError: name 'tstInt' is not defined

In [248]:
	tstStat = (tstInt!=None)

NameError: name 'tstInt' is not defined

In [249]:
# Test set
with np.load('/content/test_users_last_sold.npz', allow_pickle=True) as data:
    tstInt1 = data['test_users_last_sold']

# Extract unique user IDs and sort them
user_ids = sorted(set(pair[0] for pair in tstInt1))

# Initialize list with None for each possible user ID
max_user_id = 6416
user_purchases = [None] * max_user_id

# Fill in user IDs where applicable
for user_id in user_ids:
    # Assuming user_id starts from 1, subtract 1 for zero-based indexing
    user_purchases[user_id - 1] = user_id

tstInt = np.array(user_purchases)


FileNotFoundError: [Errno 2] No such file or directory: '/content/test_users_last_sold.npz'

In [250]:
len(tstInt)

NameError: name 'tstInt' is not defined

In [251]:
import pandas as pd
import torch
from torch.utils.data import DataLoader, TensorDataset

def prepare_data_loader_from_excel(file_path='/content/dataset.xlsx', batch_size=32, shuffle=True):
    # Load the dataset from the Excel file
    df = pd.read_excel(file_path)

    # Convert the user IDs and item IDs into tensors
    uids = torch.tensor(df['user_id'].values, dtype=torch.long)
    iids = torch.tensor(df['idCryptoPunk'].values, dtype=torch.long)  # Adjusted column name to 'item_id'

    return uids, iids

ModuleNotFoundError: No module named 'torch'

In [252]:
prepare_data_loader_from_excel()[1]

NameError: name 'prepare_data_loader_from_excel' is not defined